name: General Suggestion
description: Suggest a change or addition to the modpack
labels: [Suggestion]
body:
  - type: markdown
    attributes:
      value: |
            
        Have a general suggestion for us? Submit it here! Please use the other forms for mod suggestions & bug reports.
          
  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: What would you like added/changed?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why would you like this added/changed?
    validations:
      required: true